addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.8.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.5.0")
addSbtPlugin("me.lessis"         % "bintray-sbt"     % "0.3.0")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.0")
