addSbtPlugin("com.dwijnand"      % "sbt-travisci" % "1.0.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt" % "0.6.4")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "0.8.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "1.8.0")
addSbtPlugin("me.lessis"         % "bintray-sbt"  % "0.3.0")
