addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "0.4.10")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.8.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.6.0")
addSbtPlugin("me.lessis"         % "bintray-sbt"     % "0.3.0")
